input_data_path: "data/raw/heart_cleveland_upload.csv"
output_model_path: "models/model_svm.pkl"
metric_path: "metrics/metrics_svm.json"
splitting_params:
  val_size: 0.3
  random_state: 123
train_params:
  model_type: "SupportVectorMachine"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  features_to_drop:
    - ""
  target_col: "condition"
