name: CI
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd ml_project
          make requirements

      - name: Run tests
        run: |
          cd ml_project
          make test

      - name: Check lint
        run: |
          cd ml_project
          make lint
